settings:
  name: Element Software
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  versions:
   # Current repo stanza comes first
    - version-number: "12.7"
      url: /element-software-127
   # Additional releases newest to oldest
    - version-number: "12.8"
      url: /element-software
    - version-number: "12.5"
      url: /element-software-125
    - version-number: "12.3"
      url: /element-software-123
sidebar:
  entries:
    - title: SolidFire and Element Software Documentation 12.7
      url: /index.html
    - title: Release notes
      url: /concepts/concept_rn_relatedrn_element.html
      entries:
        - title: What's new
          url: /concepts/concept_rn_whats_new_element.html
    - section: concepts
    - title: Requirements
      url: /setup/concept_requirements_overview.html
      entries:
      - title: Networking requirements
        url: /storage/concept_prereq_networking.html
      - title: Switch configuration for clusters running Element software
        url: /storage/concept_prereq_switch_configuration_for_solidfire_clusters.html
      - title: Network port requirements
        url: /storage/reference_prereq_network_port_requirements.html
    - section: try
    - section: hardware
  # - section: esds
    - section: setup
    - section: storage
    - section: hccstorage
    - section: api
    - title: Manage storage with the Element Plug-in for vCenter Server
      url: /element-plug-in-index.html
    - title: Monitor storage with NetApp SolidFire Active IQ
      url: /monitor-storage-active-iq.html
    - section: mnode
    - section: upgrade
    - title: Earlier versions
      url: /element-earlierversions.html
    - title: Legal notices
      url: /legal-notices.html
