---
sidebar: sidebar
permalink: upgrade/concept_element_upgrade_overview.html
summary: You can keep your SolidFire Element storage system up-to-date after deployment by upgrading all NetApp storage components.
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade
---
= Upgrade sequence overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can keep your SolidFire Element storage system up-to-date after deployment by sequentially upgrading all NetApp storage components.

These components include management services, NetApp Hybrid Cloud Control, Element software, management node, and (depending on your installation) the Element Plug-in for vCenter Server.

[NOTE]
====
* Beginning November 2023, you cannot start a component upgrade using NetApp Hybrid Cloud Control or REST API because the signing key certificates (private and public) expired on November 5, 2023. You can resolve this issue by following the workaround documented in the Knowledge Base article https://kb.netapp.com/onprem/solidfire/Element_OS/SolidFire_and_HCI_upgrades_unable_to_start_due_to_upgrade_package_upload_error[SolidFire and HCI upgrades unable to start due to upgrade package upload error^].
* Beginning with Element 12.7, the SF2405 and SF9608 storage nodes and FC0025 and SF-FCN-01 FC nodes are not supported. If you attempt to upgrade one of these nodes to Element 12.7, you will see an error stating that this node is not supported by Element 12.7.
* Beginning with Element 12.5, NetApp HealthTools is no longer supported for Element software upgrades. If you are running Element 11.0 or 11.1, you must first https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools[upgrade to Element 12.3 using HealthTools^] and then upgrade to Element 12.5 or later using NetApp Hybrid Cloud Control.
====

The <<sys_upgrade,system upgrade sequence>> content describes the tasks that are needed to complete a SolidFire all-flash storage system upgrade. Ideally these procedures are performed as part of the larger upgrade sequence and not in isolation. If a component-based upgrade or update is needed, see the procedure prerequisites to ensure additional complexities are addressed.

The link:task_sf_upgrade_all_vsphere.html[vSphere upgrade sequence] including Element Plug-in for vCenter Server content describes additional pre- and post-upgrade steps required to re-install the Element Plug-in for vCenter Server.

.What you'll need

* You are running management node 11.3 or later. Newer versions of the management node have a modular architecture that provides individual services.
+
TIP: To check the version, log in to your management node and view the Element version number in the login banner. If you do not have 11.3, see link:task_hcc_upgrade_management_node.html[Upgrade your management node].

* You have upgraded your management services to at least version 2.1.326.
+
Upgrades using NetApp Hybrid Cloud Control are not available in earlier service bundle versions.

* You have ensured that the system time on all nodes is synced and that NTP is correctly configured for the storage cluster and nodes. Each node must be configured with a DNS nameserver in the per-node web UI (`https://[IP address]:442`) with no unresolved cluster faults related to time skew.

* You have scheduled sufficient time for your link:task_hcc_upgrade_element_software.html#element-upgrade-time[Element software] and link:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade[storage firmware] upgrades. When you upgrade to Element software 12.5 or later, the upgrade process time varies depending on the Element software version and firmware updates.

== [[sys_upgrade]]System upgrade sequence
You can use the following sequence to upgrade your NetApp SolidFire all-flash storage system for Element 12.5 or later.

.Steps

. link:task_hcc_update_management_services.html[Update management services from Hybrid Cloud Control].
+
IMPORTANT: If you are updating management services to version 2.16 or later and you are running a management node 11.3 to 11.8, you will need to increase your management node VM's RAM prior to updating management services.
+
IMPORTANT: You must update to the latest management services bundle before upgrading your Element software.

. link:task_hcc_upgrade_element_prechecks.html[Run Element storage health checks prior to upgrading storage].
. link:task_hcc_upgrade_element_software.html[Upgrade your Element software and storage firmware].
. link:task_hcc_upgrade_storage_firmware.html[(Optional) Upgrade your Element storage firmware only].
+
NOTE: You might perform this task when a new storage firmware upgrade becomes available outside of a major release.

. link:task_hcc_upgrade_management_node.html[(Optional) Upgrade your management node].
+
NOTE: Upgrading the management node operating system is no longer required to upgrade Element software on the storage cluster. If the management node is version 11.3 or higher, you can simply upgrade the management services to the latest version to perform Element upgrades using NetApp Hybrid Cloud Control. Follow the management node upgrade procedure for your scenario if you would like to upgrade the management node operating system for other reasons, such as security remediation.

. link:task_vcp_upgrade_plugin.html[Upgrade your Element Plug-in for vCenter Server].

[discrete]
== Find more information
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation]

// 2023 DEC 5, DOC-4719