---
permalink: concepts/concept_solidfire_concepts_nodes.html
sidebar: sidebar
keywords: what is, node, management node, storage node, fibre channel, state, pending, active
summary: 'Nodes are the hardware that is grouped into a cluster to be accessed as block storage or compute resources.'
---

= Nodes
:icons: font
:imagesdir: ../media/

[.lead]
Nodes are hardware or virtual resources that are grouped into a cluster to provide block storage and compute capabilities.

NetApp Element software defines various node roles for a cluster. The types of node roles are the following:

* <<Management node>>
* <<Storage node>>
* <<Fibre Channel node>>

<<Node states of operation,Nodes states>> vary depending on cluster association.

== Management node
A management node is a virtual machine used to upgrade and provide system services including monitoring and telemetry, manage cluster assets and settings, run system tests and utilities, and enable NetApp Support access for troubleshooting.
link:../concepts/concept_intro_management_node.html[Learn more]

== Storage node

A SolidFire storage node is a server containing a collection of drives that communicate with each other through the Bond10G network interface. Drives in the node contain block and metadata space for data storage and data management. Each node contains a factory image of NetApp Element software.

Storage nodes have the following characteristics:

* Each node has a unique name. If a node name is not specified by an administrator, it defaults to SF-XXXX, where XXXX is four random characters generated by the system.
* Each node has its own high-performance non-volatile random access memory (NVRAM) write cache to improve overall system performance and reduce write latency.
* Each node is connected to two networks, storage and management, each with two independent links for redundancy and performance. Each node requires an IP address on each network.
* You can create a cluster with new storage nodes, or add storage nodes to an existing cluster to increase storage capacity and performance.
* You can add or remove nodes from the cluster at any time without interrupting service.

== Fibre Channel node

SolidFire Fibre Channel nodes provide connectivity to a Fibre Channel switch, which you can connect to Fibre Channel clients. Fibre Channel nodes act as a protocol converter between the Fibre Channel and iSCSI protocols; this enables you to add Fibre Channel connectivity to any new or existing SolidFire cluster.

Fibre Channel nodes have the following characteristics:

* Fibre Channel switches manage the state of the fabric, providing optimized interconnections.
* The traffic between two ports flows through the switches only; it is not transmitted to any other port.
* Failure of a port is isolated and does not affect operation of other ports.
* Multiple pairs of ports can communicate simultaneously in a fabric.

== Node states of operation

[.lead]
A node can be in one of several states depending on the level of configuration.

* *Available*
+
The node has no associated cluster name and is not yet part of a cluster.

* *Pending*
+
The node is configured and can be added to a designated cluster.
+
Authentication is not required to access the node.

* *Pending Active*
+
The system is in the process of installing compatible Element software on the node. When complete, the node will move to the Active state.

* *Active*
+
The node is participating in a cluster.
+
Authentication is required to modify the node.

In each of these states, some fields are read only.

[discrete]
== Find more information
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
