---
permalink: storage/concept_intro_storage_nodes.html
sidebar: sidebar
keywords: storage nodes, management nodes, block space, metadata space, data management, storage management, Bond10G, network interface, network, metadata, data storage, storage, drives, network interfaces
summary: 'A SolidFire storage node is a server containing a collection of drives that communicate with each other through the Bond10G network interface. Drives in the node contain block and metadata space for data storage and data management.'
---

= Storage nodes
:icons: font
:imagesdir: ../media/

[.lead]
A SolidFire storage node is a server containing a collection of drives that communicate with each other through the Bond10G network interface. Drives in the node contain block and metadata space for data storage and data management.

Storage nodes have the following characteristics:

* Each node has a unique name. If a node name is not specified by an administrator, it defaults to SF-XXXX, where XXXX is four random characters generated by the system.
* Each node has its own high-performance non-volatile random access memory (NVRAM) write cache to improve overall system performance and reduce write latency.
* Each node is connected to two networks, storage and management, each with two independent links for redundancy and performance. Each node requires an IP address on each network.
* You can create a cluster with new storage nodes, or add storage nodes to an existing cluster to increase storage capacity and performance.
* You can add or remove nodes from the cluster at any time without interrupting service.
