---
permalink: storage/concept_system_manage_nodes_manage_nodes.html
sidebar: sidebar
keywords: nodes, manage, cluster, capacity rule, pairs, stranded nodes
summary: 'You can manage SolidFire storage and Fibre Channel nodes from the Nodes page of the Cluster tab.'
---

= Manage nodes
:icons: font
:imagesdir: ../media/

[.lead]
You can manage SolidFire storage and Fibre Channel nodes from the Nodes page of the Cluster tab.

If a newly added node accounts for more than 50 percent of the total cluster capacity, some of the capacity of this node is made unusable ("stranded"), so that it complies with the capacity rule. This remains the case until more storage is added. If a very large node is added that also disobeys the capacity rule, the previously stranded node will no longer be stranded, while the newly added node becomes stranded. Capacity should always be added in pairs to avoid this happening. When a node becomes stranded, an appropriate cluster fault is thrown.

== Find more information

xref:task_system_manage_nodes_adding_a_node_to_a_cluster.adoc[Add a node to a cluster]
