---
permalink: storage/task_intro_view_api_activity_in_real_time.html
sidebar: sidebar
keywords: solidfire api, element api, element os, element, viewing the API log, viewing API calls
summary: 'The Element system uses the NetApp Element API as the foundation for its features and functionality. The Element UI enables you to view various types of real-time API activity on the system as you use the interface. With the API log, you can view user-initiated and background system API activity, as well as API calls made on the page you are currently viewing.'
---

= View API activity
:icons: font
:imagesdir: ../media/

[.lead]
The Element system uses the NetApp Element API as the foundation for its features and functionality. The Element UI enables you to view various types of real-time API activity on the system as you use the interface. With the API log, you can view user-initiated and background system API activity, as well as API calls made on the page you are currently viewing.

You can use the API log to identify what API methods are used for certain tasks, and see how to use the API methods and objects to build custom applications.

For information about each method, see link:../api/index.html[Element Software API reference].

. From the Element UI navigation bar, click *API Log*.
. To modify the type of API activity displayed in the API Log window, perform the following steps:
 .. Select *Requests* to display API request traffic.
 .. Select *Responses* to display API response traffic.
 .. Filter the types of API traffic by selecting one of the following:
  *** *User Initiated*: API traffic by your activities during this web UI session.
  *** *Background Polling*: API traffic generated by background system activity.
  *** *Current Page*: API traffic generated by tasks on the page you are currently viewing.

== Find more information

* link:../api/index.html[Managing storage with the Element API]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
