---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html
sidebar: sidebar
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s
summary: 'You can change the default Intelligent Platform Management Interface (IPMI) administrator password as soon as you have remote IPMI access to the node. You might want to do this if there were any installation updates.'
---

= Change default IPMI password for nodes
:icons: font
:imagesdir: ../media/

[.lead]
You can change the default Intelligent Platform Management Interface (IPMI) administrator password as soon as you have remote IPMI access to the node. You might want to do this if there were any installation updates.

For details about configuring IPM access for nodes, see link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html[Configure IPMI for each node^].

You can change the IPM password for these nodes:

* H410S nodes
* H610S nodes

== Change the default IPMI password for H410S nodes
You should change the default password for the IPMI administrator account on each storage node as soon as you configure the IPMI network port.

.What you'll need
You should have configured the IPMI IP address for each storage node.

.Steps
. Open a web browser on a computer that can reach the IPMI network and browse to the IPMI IP address for the node.
. Enter the user name `ADMIN` and password `ADMIN` in the login prompt.
. Upon logging in, click the *Configuration* tab.
. Click *Users*.
. Select the `ADMIN` user and click *Modify User*.
. Select the *Change Password* check box.
. Enter a new password in the *Password* and *Confirm Password* fields.
. Click *Modify*, and then click *OK*.
. Repeat this procedure for any other H410S nodes with default IPMI passwords.

== Change the default IPMI password for H610S nodes
You should change the default password for the IPMI administrator account on each storage node as soon as you configure the IPMI network port.

.What you'll need
You should have configured the IPMI IP address for each storage node.

.Steps
. Open a web browser on a computer that can reach the IPMI network and browse to the IPMI IP address for the node.
. Enter the user name `root` and password `calvin` in the login prompt.
. Upon logging in, click the menu navigation icon at the top left of the page to open the sidebar drawer.
. Click *Settings*.
. Click *User Management*.
. Select the *Administrator* user from the list.
. Enable the *Change Password* check box.
. Enter a new, strong password in the *Password* and *Confirm Password* fields.
. Click *Save* at the bottom of the page.
. Repeat this procedure for any other H610S nodes with default IPMI passwords.

== Find more information
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
