---
permalink: storage/task_data_protection_edit_a_snapshot_schedule.html
sidebar: sidebar
keywords: snapshot schedule, edit, modify
summary: 'You can modify existing snapshot schedules. After modification, the next time the schedule runs it uses the updated attributes. Any snapshots created by the original schedule remain on the storage system.'
---

= Edit a snapshot schedule
:icons: font
:imagesdir: ../media/

[.lead]
You can modify existing snapshot schedules. After modification, the next time the schedule runs it uses the updated attributes. Any snapshots created by the original schedule remain on the storage system.

.Steps
. Click *Data Protection* > *Schedules*.
. Click the *Actions* icon for the schedule you want to change.
. In the resulting menu, click *Edit*.
. In the *Volume IDs CSV* field, modify the single volume ID or comma-separated list of volume IDs currently included in the snapshot operation.
. To pause or resume the schedule, select from the following options:
 ** To pause an active schedule, select *Yes* from the *Manually Pause Schedule* list.
 ** To resume a paused schedule, select *No* from the *Manually Pause Schedule* list.
. Enter a different name for the schedule in the *New Schedule Name* field if desired.
. To change the schedule to run on different days of the week or month, select *Schedule Type* and change the schedule from the options provided.
. *Optional:* Select *Recurring Schedule* to repeat the snapshot schedule indefinitely.
. *Optional:* Enter or modify the name for the new snapshot in the *New Snapshot Name* field.
+
If you leave the field blank, the system uses the time and date of the snapshot's creation as the name.

. *Optional:* Select the *Include Snapshots in Replication When Paired* check box to ensure that the snapshots are captured in replication when the parent volume is paired.
. To change the retention setting, select from the following options:
 ** Click *Keep Forever* to retain the snapshot on the system indefinitely.
 ** Click *Set Retention Period* and use the date spin boxes to select a length of time for the system to retain the snapshot.
. Click *Save Changes*.
