---
permalink: storage/task_replication_pair_cluster_using_pairing_key.html
sidebar: sidebar
keywords: remote replication, pairing key, pairing clusters
summary: 'If you have cluster administrator access to a local cluster but not the remote cluster, you can pair the clusters using a pairing key. A pairing key is generated on a local cluster and then sent securely to a cluster administrator at a remote site to establish a connection and complete the cluster pairing for real-time replication.'
---

= Pair clusters using a pairing key
:icons: font
:imagesdir: ../media/

[.lead]
If you have cluster administrator access to a local cluster but not the remote cluster, you can pair the clusters using a pairing key. A pairing key is generated on a local cluster and then sent securely to a cluster administrator at a remote site to establish a connection and complete the cluster pairing for real-time replication.

. On the local cluster, select *Data Protection* > *Cluster Pairs*.
. Click *Pair Cluster*.
. Click *Start Pairing* and click *No* to indicate that you do not have access to the remote cluster.
. Click *Generate Key*.
+
NOTE: This action generates a text key for pairing and creates an unconfigured cluster pair on the local cluster. If you do not complete the procedure, you will need to manually delete the cluster pair.

. Copy the cluster pairing key to your clipboard.
. Make the pairing key accessible to the cluster administrator at the remote cluster site.
+
NOTE: The cluster pairing key contains a version of the MVIP, user name, password, and database information to permit volume connections for remote replication. This key should be treated in a secure manner and not stored in a way that would allow accidental or unsecured access to the user name or password.
+
IMPORTANT: Do not modify any of the characters in the pairing key. The key becomes invalid if it is modified.

. On the remote cluster, select *Data Protection* > *Cluster Pairs*.
. Click *Pair Cluster*.
. Click *Complete Pairing* and enter the pairing key in the *Pairing Key* field (paste is the recommended method).
. Click *Complete Pairing*.

== Find more information

* xref:task_replication_pair_cluster_using_mvip.adoc[Pair clusters using MVIP]
* https://www.youtube.com/watch?v=1ljHAd1byC8&feature=youtu.be[Pairing clusters using a cluster pairing key (video)]
