---
permalink: storage/task-element-replication-enable-snapmirror-cluster.html
sidebar: sidebar
keywords: ontap, cli, enable, snapmirror, element, cluster
summary: "You must enable SnapMirror on the Element cluster before you can create a replication relationship. You can only perform this task in the Element software web UI or using the API methods."
---
= Enable SnapMirror on the Element cluster
:icons: font
:imagesdir: ../media/

[.lead]
You must enable SnapMirror on the Element cluster before you can create a replication relationship. You can only perform this task in the Element software web UI or using the link:../api/reference_element_api_enablefeature.html[API method].

.Before you begin

* The Element cluster must be running NetApp Element software version 10.1 or later.
* SnapMirror can only be enabled for Element clusters used with NetApp ONTAP volumes.

.About this task

The Element system comes with SnapMirror disabled by default. SnapMirror is not automatically enabled as part of a new installation or upgrade.

[NOTE]
====
Once enabled, SnapMirror cannot be disabled. You can only disable the SnapMirror feature and restore the default settings by returning the cluster to the factory image.
====

.Steps

. Click *Clusters* > *Settings*.
. Find the cluster-specific settings for SnapMirror.
. Click *Enable SnapMirror*.

// 2024 AUG 30, ONTAPDOC-1436