---
permalink: storage/task_data_protection_restore_volume_from_backup_on_solidfire.html
sidebar: sidebar
keywords: volume restore, solidfire storage cluster
summary: 'You can restore a volume from a backup on a SolidFire storage cluster.'
---

= Restore a volume from backup on a SolidFire storage cluster
:icons: font
:imagesdir: ../media/

[.lead]
You can restore a volume from a backup on a SolidFire storage cluster.

When backing up or restoring from one cluster to another, the system generates a key to be used as authentication between the clusters. This bulk volume write key allows the source cluster to authenticate with the destination cluster, providing a level of security when writing to the destination volume. As part of the backup or restore process, you need to generate a bulk volume write key from the destination volume before starting the operation.

. On the destination cluster, click *Management* > *Volumes*.
. Click the Actions icon for the volume you want to restore.
. In the resulting menu, click *Restore from*.
. In the *Integrated Restore* dialog box, under *Restore from*, select *SolidFire*.
. Select the option that matches the backup under *Data Format*:
 ** *Native*: A compressed format readable only by SolidFire storage systems.
 ** *Uncompressed*: An uncompressed format compatible with other systems.
. Click *Generate Key*.
. Copy the *Bulk Volume Write Key* information to the clipboard.
. On the source cluster, click *Management* > *Volumes*.
. Click the Actions icon for the volume you want to use for the restore.
. In the resulting menu, click *Backup to*.
. In the *Integrated Backup* dialog box, select *SolidFire* under *Backup to*.
. Select the option that matches the backup under *Data Format*.
. Enter the management virtual IP address of the destination volume's cluster in the *Remote Cluster MVIP* field.
. Enter the remote cluster user name in the *Remote Cluster Username* field.
. Enter the remote cluster password in the *Remote Cluster Password* field.
. Paste the key from your clipboard into the *Bulk Volume Write Key* field.
. Click *Start Read*.
