---
permalink: storage/task_post_deploy_configure_system_options.html
sidebar: sidebar
keywords: deployment, post deployment options, credentials, components, FIPS security, passwords, MFA, multifactor authentication, mutli-factor authentication, security, EKM, key management, external key management, FIPS
summary: 'After you set up your SolidFire system, you might want to perform some optional tasks. Additionally, you can configure settings for multi-factor authentication, external key management, and Federal Information Processing Standards \(FIPS\) security.'
---

= Configure SolidFire system options after deployment
:icons: font
:imagesdir: ../media/

[.lead]
After you set up your SolidFire system, you might want to perform some optional tasks.

If you change credentials in the system, you might want to know the impact on other components.

Additionally, you can configure settings for multi-factor authentication, external key management, and Federal Information Processing Standards (FIPS) security.
You should also look at updating passwords when needed.


== Find more information
* link:task_post_deploy_credentials.html[Change credentials in NetApp HCI and NetApp SolidFire]
* link:reference_post_deploy_change_default_ssl_certificate.html[Change the Element software default SSL certificate]
* link:task_post_deploy_credential_change_ipmi_password.html[Change the IPMI password for nodes]
* link:concept_system_manage_mfa_enable_multi_factor_authentication.html[Enable multi-factor authentication]
* link:concept_system_manage_key_get_started_with_external_key_management.html[Get started with external key management]
* link:task_system_manage_fips_create_a_cluster_supporting_fips_drives.html[Create a cluster supporting FIPS drives]
