---
permalink: storage/task_data_protection_create_a_volume_snapshot.html
sidebar: sidebar
keywords: volume snapshot, create, active volume, preserve volume
summary: 'You can create a snapshot of an active volume to preserve the volume image at any point in time. You can create up to 32 snapshots for a single volume.'
---

= Create a volume snapshot
:icons: font
:imagesdir: ../media/

[.lead]
You can create a snapshot of an active volume to preserve the volume image at any point in time. You can create up to 32 snapshots for a single volume.

. Click *Management* > *Volumes*.
. Click the *Actions* icon for the volume you want to use for the snapshot.
. In the resulting menu, select *Snapshot*.
. In the *Create Snapshot of Volume* dialog box, enter the new snapshot name.
. *Optional:* Select the *Include Snapshot in Replication When Paired* check box to ensure that the snapshot is captured in replication when the parent volume is paired.
. To set the retention for the snapshot, select from one of the following options:
 ** Click *Keep Forever* to retain the snapshot on the system indefinitely.
 ** Click *Set Retention Period* and use the date spin boxes to choose a length of time for the system to retain the snapshot.
. To take a single, immediate snapshot, perform the following steps:
 .. Click *Take Snapshot Now*.
 .. Click**Create Snapshot**.
. To schedule the snapshot to run at a future time, perform the following steps:
 .. Click *Create Snapshot Schedule*.
 .. Enter a *New Schedule Name*.
 .. Choose a *Schedule Type* from the list.
 .. *Optional:* Select the *Recurring Schedule* check box to repeat the scheduled snapshot periodically.
 .. Click *Create Schedule*.

== Find more information

xref:task_data_protection_schedule_a_snapshot_task.adoc[Schedule a snapshot]
