---
permalink: setup/task_setup_create_a_storage_cluster.html
sidebar: sidebar
keywords:
summary: 'You can create a storage cluster after you have configured all of the individual nodes. When you create a cluster, a cluster administrator user account is automatically created for you. The cluster administrator has permission to manage all cluster attributes and can create other cluster administrator accounts.'
---

= Create a storage cluster
:icons: font
:imagesdir: ../media/

[.lead]
You can create a storage cluster after you have configured all of the individual nodes. When you create a cluster, a cluster administrator user account is automatically created for you. The cluster administrator has permission to manage all cluster attributes and can create other cluster administrator accounts.

.What you'll need
* You have installed the management node.
* You have configured all of the individual nodes.

.About this task
During new node configuration, 1G or 10G Management IP (MIP) addresses are assigned to each node. You must use one of the node IP addresses created during configuration to open the Create a New Cluster page. The IP address you use depends on the network you have chosen for cluster management.

[IMPORTANT]
====
If you want to enable cluster-wide link:../concepts/concept_solidfire_concepts_security.html#encryption-at-rest-software[software encryption at rest] for SolidFire all-flash storage clusters, you must do so during cluster creation. Beginning with Element 12.5, you must enable software encryption at rest in the Create Cluster UI during cluster creation. For Element 12.3.x and earlier, you must create the cluster using the link:../api/reference_element_api_createcluster.html[CreateCluster] API method and change the enableSoftwareEncryptionAtRest parameter to `true`. After software encryption at rest is enabled on the cluster, it cannot be disabled. You can link:../storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html[enable and disable] Hardware-based encryption at rest after cluster creation.
====

[NOTE]
===============================
When creating a new cluster, consider the following:

* If you are using storage nodes that reside in a shared chassis, you might want to consider designing for chassis-level failure protection using the protection domains feature.
* If a shared chassis in not in use, you can define a custom protection domain layout.
===============================

.Steps
. In a browser window, enter `\https://MIP:443`, where MIP is the management node IP address.
. In Create a New Cluster, enter the following information:
 ** Management VIP: Routable virtual IP on the 1GbE or 10GbE network for network management tasks.
+
NOTE: You can create a new cluster using IPv4 or IPv6 addressing.

 ** iSCSI (storage) VIP: Virtual IP on the 10GbE network for storage and iSCSI discovery.
+
NOTE: You cannot change the MVIP, SVIP, or cluster name after you create the cluster.

 ** User name: The primary cluster administrator user name for authenticated access to the cluster. You must save the user name for future reference.
+
NOTE: You can use uppercase and lowercase letters, special characters, and numbers for the user name and password.

 ** Password: Password for authenticated access to the cluster. You must save the password for future reference.
Two-way data protection is enabled by default. You cannot change this setting.
. Read the End User License Agreement, and select *I Agree*.
. *Optional*: In the Nodes list, ensure that the check boxes for nodes that should not be included in the cluster are not selected.
. Select *Create Cluster*.
+
The system might take several minutes to create the cluster depending on the number of nodes in the cluster. On a properly configured network, a small cluster of five nodes should take less than one minute. After the cluster is created, the Create a New Cluster window is redirected to the MVIP URL address for the cluster and displays the Element UI.

== For more information

* link:../api/index.html[Managing storage with the Element API]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
// 2022 DEC 12, DOC-4643 