---
permalink: api/concept_element_api_drive_api_methods.html
sidebar: sidebar
keywords: drive,API,methods,method
summary: 'You can use drive API methods to add and manage drives that are available to a storage cluster. When you add a storage node to the storage cluster or install new drives in an existing storage node, the drives are available to be added to the storage cluster.'
---

= Drive API methods
:icons: font
:imagesdir: ../media/

[.lead]
You can use drive API methods to add and manage drives that are available to a storage cluster. When you add a storage node to the storage cluster or install new drives in an existing storage node, the drives are available to be added to the storage cluster.

* xref:reference_element_api_adddrives.adoc[AddDrives]
* xref:reference_element_api_getdrivehardwareinfo.adoc[GetDriveHardwareInfo]
* xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
* xref:reference_element_api_listdrives.adoc[ListDrives]
* xref:reference_element_api_listdrivestats.adoc[ListDriveStats]
* xref:reference_element_api_removedrives.adoc[RemoveDrives]
* xref:reference_element_api_secureerasedrives.adoc[SecureEraseDrives]

== Find more information
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[Documentation for earlier versions of NetApp SolidFire and Element products^]
