---
permalink: api/reference_element_api_clusterconfig.html
sidebar: sidebar
keywords: objects,object,clusterConfig
summary: 'The clusterConfig object returns information the node uses to communicate with the cluster.'
---

= clusterConfig
:icons: font
:imagesdir: ../media/

[.lead]
The `clusterConfig` object returns information the node uses to communicate with the cluster.

== Object members

This object contains the following members:

[options="header"]
|===
|Name |Description |Type
a|
`cipi`
a|
Network interface used for cluster communication.
a|
string
a|
`cluster`
a|
Unique name of the cluster.
a|
string
a|
`encryptionCapable`
a|
Specifies whether the node supports encryption.
a|
boolean
a|
`ensemble`
a|
Nodes that are participating in the cluster.
a|
string array
a|
`fipsDriveConfiguration`
a|
Specifies whether the node supports FIPS 140-2 certified drives.
a|
boolean
a|
`hasLocalAdmin`
a|
Specifies whether the cluster has a local administrator.
a|
boolean
a|
`mipi`
a|
Network interface used for node management.
a|
string
a|
`name`
a|
Unique identifier for the cluster.
a|
string
a|
`nodeID`
a|
Unique identifier for the node.
a|
integer
a|
`pendingNodeID`
a|
Unique identifier for the pending node.
a|
integer
a|
`role`
a|
Identifies the role of the node.
a|
string
a|
`sipi`
a|
Network interface used for storage.
a|
string
a|
`state`
a|
Indicates the state of the node.
a|
string
a|
`version`
a|
Indicates the version of the node.
a|
string
|===
