---
permalink: api/reference_element_api_listsnapmirroraggregates.html
sidebar: sidebar
keywords: snapmirror,aggregate,aggregates,list,listing,listsnapmirroraggregates
summary: 'The Element software web UI uses the ListSnapMirrorAggregates method to list all SnapMirror aggregates that are available on the remote ONTAP system. An aggregate describes a set of physical storage resources.'
---

= ListSnapMirrorAggregates
:icons: font
:imagesdir: ../media/

[.lead]
The Element software web UI uses the `ListSnapMirrorAggregates` method to list all SnapMirror aggregates that are available on the remote ONTAP system. An aggregate describes a set of physical storage resources.

== Parameter

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
snapMirrorEndpointID
a|
Return only the aggregates associated with the specified endpoint ID. If no endpoint ID is provided, the system lists aggregates from all known SnapMirror endpoints.
a|
integer
a|
None
a|
No
|===

== Return value

This method has the following return value:

|===
|Name |Description |Type
a|
snapMirrorAggregates
a|
A list of the aggregates available on the ONTAP storage system.
a|
xref:reference_element_api_snapmirroraggregate.adoc[snapMirrorAggregate] array
|===

== New since version

10.1
