---
permalink: api/reference_element_api_listidpconfigurations.html
sidebar: sidebar
keywords: configs configurations,idp configs,list
summary: 'You can use the ListIdpConfigurations method to list configurations for third-party IdPs. Optionally, you can provide either the enabledOnly flag to retrieve the currently enabled IdP configuration or an IdP metadata UUID or IdP name to query information for a specific IdP configuration.'
---

= ListIdpConfigurations
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ListIdpConfigurations` method to list configurations for third-party IdPs. Optionally, you can provide either the `enabledOnly` flag to retrieve the currently enabled IdP configuration or an IdP metadata UUID or IdP name to query information for a specific IdP configuration.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
enabledOnly
a|
Filters the result to return the currently enabled IdP configuration.
a|
boolean
a|
None
a|
No
a|
idpConfigurationID
a|
UUID for the third-party IdP configuration.
a|
UUID
a|
None
a|
No
a|
idpName
a|
Retrieves IdP configuration information for a specific IdP name.
a|
string
a|
None
a|
No
|===

== Return values

This method has the following return value:

|===
|Name |Description |Type
a|
idpConfigInfos
a|
Information on the third-party IdP configuration(s).
a|
link:reference_element_api_idpconfiginfo.html[idpConfigInfo] array
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "method": "ListIdpConfigurations",
  "params": {}
}
----

== Response example

This method returns a response similar to the following example:

----
{
    "result": {
        "idpConfigInfo": {
        "enabled": true,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ...</Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MI...BHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----

== New since version

12.0
