---
permalink: api/reference_element_api_getsnmpstate.html
sidebar: sidebar
keywords: snmp,state,get,getting,getsnmpstate
summary: 'You can use the GetSnmpState method to get the current state of the SNMP feature.'
---

= GetSnmpState
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `GetSnmpState` method to get the current state of the SNMP feature.

== Parameters

This method has no input parameters.

== Return values

This method has the following return values:

[options="header"]
|===
|Name |Description |Type
a|
enabled
a|
Possible values:

* true
* false

Default value is false. Returns true if the nodes in the cluster are configured for SNMP.
a|
boolean
a|
snmpV3Enabled
a|
Possible values:

* true
* false

Default value is false. Returns true if the nodes in the cluster are configured for SNMP v3.
a|
boolean
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "method": "GetSnmpState",
  "params": {},
  "id" : 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id" : 1,
  "result" : {
   "enabled": true,
   "snmpV3Enabled": false
   }
}
----

== New since version

9.6

== Find more information

xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL]
