---
permalink: api/reference_element_api_listprotectiondomainlevels.html
sidebar: sidebar
keywords: list,listing,protection,domain,levels,level,listprotectiondomainlevels
summary: 'You can use the ListProtectionDomainLevels method to list the tolerance and resiliency levels of the storage cluster. Tolerance levels indicate the cluster’s ability to continue reading and writing data in the event of a failure, and resiliency levels indicate the storage cluster’s ability to automatically heal itself from one or more failures.'
---

= ListProtectionDomainLevels
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ListProtectionDomainLevels` method to list the tolerance and resiliency levels of the storage cluster. Tolerance levels indicate the cluster's ability to continue reading and writing data in the event of a failure, and resiliency levels indicate the storage cluster's ability to automatically heal itself from one or more failures.

== Parameter

This method has no input parameter.

== Return values

This method has the following return values:

[options="header"]
|===
|Name |Description |Type
a|
protectionDomainLevels
a|
A list of the different protection domain levels, where each supplies the storage cluster's tolerance and resiliency information.
a|
xref:reference_element_api_protectiondomainlevel.adoc[protectionDomainLevel]
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "method": "ListProtectionDomainLevels",
  "params": {},
  "id" : 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
	"id": 1,
	"result": {
		"protectionDomainLevels": [
			{
				"protectionDomainType": "node",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			},
			{
				"protectionDomainType": "chassis",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			}
		]
	}
}
----

== New since version

11.0
