---
permalink: api/reference_element_api_addnodes.html
sidebar: sidebar
keywords: addnodes,node,add,adding,nodes,cluster
summary: 'You can use the AddNodes method to add one or more new nodes to a cluster.'
---

= AddNodes
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `AddNodes` method to add one or more new nodes to a cluster.

When a node that is not configured starts up for the first time, you are prompted to configure the node. Once you configure the node, it is registered as a "pending node" with the cluster. Storage clusters running Element software automatically image a node to the version on the cluster. When you add a pending node, the method response includes an asyncHandle value that you can use with the `GetAsyncResult` method to query the status of the automatic imaging process.

The process of adding a Fibre Channel node is the same as adding Element iSCSI storage nodes to a cluster. Fibre Channel nodes are registered in the system with a NodeID. When they become accessible, they are put in a "pending node" status. The `ListAllNodes` method will return the pendingNodeID for iSCSI nodes as well as any Fibre Channel nodes that are available to add to the cluster.

When you add a node to a cluster that you have configured for virtual networking, the system requires a sufficient number of virtual storage IP addresses to allocate a virtual IP to the new node. If there are no virtual IP addresses available for the new node, the `AddNode` operation fails. Use the `ModifyVirtualNetwork` method to add more storage IP addresses to your virtual network.

Once you add a node, any drives on the node are made available and you can add them using the `AddDrives` method to increase the storage capacity of the cluster.

NOTE: It may take several seconds after adding a new node for it to start up and register its drives as available.

== Parameter

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
autoInstall
a|
If true, a return to factory image (RTFI) will be performed on the node upon adding. The default behavior is to perform RTFI. If the `cEnableAutoInstall` cluster constant is false, it takes priority over this parameter. If an upgrade is in progress, the RTFI process will not happen regardless of the value for this parameter.
a|
boolean
a|
None
a|
No
a|
pendingNodes
a|
Pending NodeIDs for the nodes to be added. You can list all pending nodes using the ListPendingNodes method.
a|
integer array
a|
None
a|
Yes
|===

== Return value

This method has the following return value:

|===
|Name |Description |Type
a|
autoInstall
a|
Whether or not the added nodes are being returned to the factory image.
a|
boolean
a|
nodes
a|
An array of objects mapping the previous "pendingNodeID" to the "nodeID". When you add a pending node that is running an incompatible software version, this array includes an asyncHandle value that you can use with the GetAsyncResult method to query the status of the automatic imaging process.
a|
JSON object array
|===

== Request example

Requests for this method are similar to the following example:

----
{
   "method": "AddNodes",
   "params": {
     "autoInstall" : true,
     "pendingNodes" : [1]
   },
   "id":1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  id: null,
  result: {
    autoInstall: true,
    nodes: [
      {
        activeNodeKey: "giAm2ep1hA",
        assignedNodeID: 6,
        asyncHandle: 3,
        cip: "10.10.5.106",
        mip: "192.168.133.106",
        pendingNodeID: 2,
        platformInfo: {
          chassisType: "R620",
          cpuModel: "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
          nodeMemoryGB: 72,
          nodeType: "SF3010"
        },
        sip: "10.10.5.106",
        softwareVersion: "9.0.0.1077"
      }
    ]
  }
}
----

== New since version

9.6

== Find more information

* xref:reference_element_api_adddrives.adoc[AddDrives]
* xref:reference_element_api_getasyncresult.adoc[GetAsyncResult]
* xref:reference_element_api_listallnodes.adoc[ListAllNodes]
* xref:reference_element_api_modifyvirtualnetwork.adoc[ModifyVirtualNetwork]
