---
permalink: api/reference_element_api_listsnapmirrorpolicies.html
sidebar: sidebar
keywords: snapmirror,policy,policies,list,listing,ontap,listsnapmirrorpolicies
summary: 'The Element software web UI uses the ListSnapMirrorPolicies method to list all SnapMirror policies on a remote ONTAP system.'
---

= ListSnapMirrorPolicies
:icons: font
:imagesdir: ../media/

[.lead]
The Element software web UI uses the `ListSnapMirrorPolicies` method to list all SnapMirror policies on a remote ONTAP system.

== Parameter

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
snapMirrorEndpointID
a|
List only the policies associated with the specified endpoint ID. If no endpoint ID is provided, the system lists policies from all known SnapMirror endpoints.
a|
integer
a|
None
a|
No
|===

== Return value

This method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
snapMirrorPolicies
a|
A list of the SnapMirror policies on the ONTAP storage system.
a|
xref:reference_element_api_snapmirrorpolicy.adoc[snapMirrorPolicy] array
|===

== New since version

10.1
