---
permalink: api/reference_element_api_enableidpauthentication.html
sidebar: sidebar
keywords: IdP,idp,authentication,enable
summary: 'You can use the EnableIdpAuthentication method to enable support for authentication using third-party IdPs for the cluster. Once IdP authentication is enabled, LDAP and cluster admins are no longer able to access the cluster via supported UIs and any active authenticated sessions are invalidated/disconnected. Only users authenticated by third party IdPs are able to access the cluster via supported UIs.'
---

= EnableIdpAuthentication
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `EnableIdpAuthentication` method to enable support for authentication using third-party IdPs for the cluster. Once IdP authentication is enabled, LDAP and cluster admins are no longer able to access the cluster via supported UIs and any active authenticated sessions are invalidated/disconnected. Only users authenticated by third party IdPs are able to access the cluster via supported UIs.

== Parameters

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
idpConfigurationID
a|
UUID for the third-party IdP configuration. If only one IdP configuration exists, then the default is to enable that configuration. If you have only a single IdpConfiguration, you need not provide the idpConfigurationID parameter.

a|
UUID
a|
None
a|
No
|===

== Return values

This method has no return values.

== Request example

Requests for this method are similar to the following example:

----
{
  "method": "EnableIdpAuthentication",
  "params": {
    "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
  }
}
----

== Response example

This method returns a response similar to the following example:

----
{
"result": {}
}
----

== New since version

12.0
