---
permalink: api/reference_element_api_listsnapmirrorschedules.html
sidebar: sidebar
keywords: snapmirror,schedule,schedules,list,listing,listsnapmirrorschedules,ontap
summary: 'The Element software web UI uses the ListSnapMirrorSchedules method to get a list of schedules that are available on a remote ONTAP cluster.'
---

= ListSnapMirrorSchedules
:icons: font
:imagesdir: ../media/

[.lead]
The Element software web UI uses the `ListSnapMirrorSchedules` method to get a list of schedules that are available on a remote ONTAP cluster.

== Parameter

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
snapMirrorEndpointID
a|
If provided, the system lists the schedules of the endpoint with the specified SnapMirror endpoint ID. If not provided, the system lists the schedules of all known SnapMirror endpoints.
a|
integer
a|
None
a|
No
|===

== Return value

This method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
snapMirrorSchedules
a|
A list of the SnapMirror schedules on the remote ONTAP cluster.
a|
xref:reference_element_api_snapmirrorjobschedulecroninfo.adoc[snapMirrorJobScheduleCronInfo] array
|===

== New since version

10.1
