---
permalink: api/reference_element_api_listvolumestats.html
sidebar: sidebar
keywords: volumes,volume,stats,list,listing,listvolumestats,activity
summary: 'You can use the ListVolumeStats method to get high-level activity measurements for a single volume, list of volumes, or all volumes \(if you omit the volumeIDs parameter\). Measurement values are cumulative from the creation of the volume.'
---

= ListVolumeStats
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ListVolumeStats` method to get high-level activity measurements for a single volume, list of volumes, or all volumes (if you omit the volumeIDs parameter). Measurement values are cumulative from the creation of the volume.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
includeVirtualVolumes
a|
Virtual volumes are included in the response by default. To exclude virtual volumes, set to false.
a|
boolean
a|
true
a|
No
a|
volumeIDs
a|
A list of volumes from which to retrieve activity information.
a|
integer array
a|
No
a|
No
|===

== Return value

This method has the following return value:

|===
|Name |Description |Type
a|
volumeStats
a|
List of volume activity information.
a|
xref:reference_element_api_volumestats.adoc[volumeStats] array
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "method": "ListVolumeStats",
    "params": {
        "volumeIDs": [1]
    },
    "id": 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 1,
        "actualIOPS": 0,
        "asyncDelay": null,
        "averageIOPSize": 0,
        "burstIOPSCredit": 30000,
        "clientQueueDepth": 0,
        "desiredMetadataHosts": null,
        "latencyUSec": 0,
        "metadataHosts": {
          "deadSecondaries": [],
          "liveSecondaries": [
            47
          ],
          "primary": 33
        },
        "nonZeroBlocks": 22080699,
        "readBytes": 657262370816,
        "readBytesLastSample": 0,
        "readLatencyUSec": 0,
        "readOps": 160464446,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "throttle": 0,
        "timestamp": "2016-03-09T19:39:15.771697Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
          1
        ],
        "volumeID": 1,
        "volumeSize": 107374182400,
        "volumeUtilization": 0,
        "writeBytes": 219117547520,
        "writeBytesLastSample": 0,
        "writeLatencyUSec": 0,
        "writeOps": 53495495,
        "writeOpsLastSample": 0,
        "zeroBlocks": 4133701
      }
    ]
  }
}
----

== New since version

9.6
