---
permalink: api/reference_element_api_listvirtualvolumes.html
sidebar: sidebar
keywords: virtual,volume,volumes,vvol,list,listing,listvirtualvolumes
summary: 'You can use the ListVirtualVolumes method to list the virtual volumes currently in the system. You can use this method to list all virtual volumes, or only list a subset.'
---

= ListVirtualVolumes
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ListVirtualVolumes` method to list the virtual volumes currently in the system. You can use this method to list all virtual volumes, or only list a subset.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
details
a|
The level of detail in the response. Possible values:

* true: Include more details about each VVol in the response.
* false: Include the standard level of detail about each VVol in the response.

a|
boolean
a|
False
a|
No
a|
limit
a|
The maximum number of virtual volumes to list.
a|
integer
a|
10000
a|
No
a|
recursive
a|
Specifies whether to include information about the children of each VVol in the response or not. Possible values:

* true: Include information about the children of each VVol in the response.
* false: Do not include information about the children of each VVol in the response.

a|
boolean
a|
False
a|
No
a|
startVirtualVolumeID
a|
The ID of the virtual volume at which to begin the list in the response.
a|
UUIDType
a|
None
a|
No
a|
virtualVolumeIDs
a|
A list of virtual volume IDs for which to retrieve information. If you omit this parameter, the method returns information about only these virtual volumes.
a|
virtualVolumeID UUID array
a|
None
a|
No
|===

== Return values

This method has the following return values:

|===
|Name |Description |Type
a|
nextVirtualVolumeID
a|
The ID of the next virtual volume in the list.
a|
UUID
a|
virtualVolumes
a|
A list of objects describing the virtual volumes currently in the system.
a|
xref:reference_element_api_virtualvolume.adoc[virtualVolume] array
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "method": "ListVirtualVolumes",
    "params": {
    },
    "id": 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 1,
  "result": {
    "nextVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
    "virtualVolumes": [
      {
        "bindings": [
          177
        ],
        "children": [],
        "metadata": {
          "SFProfileId": "f4e5bade-15a2-4805-bf8e-52318c4ce443",
          "SFgenerationId": "0",
          "VMW_ContainerId": "abaab415-bedc-44cd-98b8-f37495884db0",
          "VMW_VVolName": "asdf",
          "VMW_VVolType": "Config",
          "VMW_VmID": "502e0676-e510-ccdd-394c-667f6867fcdf",
          "VMW_VvolProfile": "f4e5bade-15a2-4805-bf8e-52318c4ce443:0"
        },
        "parentVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
        "snapshotID": 0,
        "snapshotInfo": null,
        "status": "done",
        "storageContainer": {
          "accountID": 1,
          "initiatorSecret": "B5)D1y10K)8IDN58",
          "name": "test",
          "protocolEndpointType": "SCSI",
          "status": "active",
          "storageContainerID": "abaab415-bedc-44cd-98b8-f37495884db0",
          "targetSecret": "qgae@{o{~8\"2U)U^"
        },
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeType": "config",
        "volumeID": 166,
        "volumeInfo": null
      }
    ]
  }
}
----

== New since version

9.6
