---
permalink: api/reference_element_api_getdrivestats.html
sidebar: sidebar
keywords: drive,drives,stats,get,getting,getdrivestats
summary: 'You can use the GetDriveStats method to get high-level activity measurements for a single drive. Values are cumulative from the addition of the drive to the cluster. Some values are specific to block drives. Statistical data is returned for either block or metadata drive types when you run this method.'
---

= GetDriveStats
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `GetDriveStats` method to get high-level activity measurements for a single drive. Values are cumulative from the addition of the drive to the cluster. Some values are specific to block drives. Statistical data is returned for either block or metadata drive types when you run this method.

== Parameter

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
driveID
a|
ID of the drive for the request.
a|
integer
a|
None
a|
Yes
|===

== Return value

This method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
driveStats
a|
Drive activity information for the specified driveID.
a|
xref:reference_element_api_drivestats.adoc[driveStats]
|===

== Request example

Requests for this method are similar to the following example:

----
{
   "method": "GetDriveStats",
   "params": {
     "driveID": 3
   },
   "id" : 1
}
----

== Response example (block drive)

This method returns a response similar to the following example for a block drive:

----
{
  "id": 1,
  "result": {
    "driveStats": {
      "driveID": 10,
      "failedDieCount": 0,
      "lifeRemainingPercent": 99,
      "lifetimeReadBytes": 26471661830144,
      "lifetimeWriteBytes": 13863852441600,
      "powerOnHours": 33684,
      "readBytes": 10600432105,
      "readOps": 5101025,
      "reallocatedSectors": 0,
      "reserveCapacityPercent": 100,
      "timestamp": "2016-10-17T20:23:45.456834Z",
      "totalCapacity": 300069052416,
      "usedCapacity": 6112226545,
      "usedMemory": 114503680,
      "writeBytes": 53559500896,
      "writeOps": 25773919
    }
  }
}
----

== Response example (volume metadata drive)

This method returns a response similar to the following example for a volume metadata drive:

----
{
  "id": 1,
  "result": {
    "driveStats": {
      "activeSessions": 8,
      "driveID": 12,
      "failedDieCount": 0,
      "lifeRemainingPercent": 100,
      "lifetimeReadBytes": 2308544921600,
      "lifetimeWriteBytes": 1120986464256,
      "powerOnHours": 16316,
      "readBytes": 1060152152064,
      "readOps": 258826209,
      "reallocatedSectors": 0,
      "reserveCapacityPercent": 100,
      "timestamp": "2016-10-17T20:34:52.456130Z",
      "totalCapacity": 134994670387,
      "usedCapacity": null,
      "usedMemory": 22173577216,
      "writeBytes": 353346510848,
      "writeOps": 86266238
    }
  }
}
----

== New since version

9.6

== Find more information

xref:reference_element_api_listdrives.adoc[ListDrives]
