---
permalink: api/reference_element_api_listsnapmirrorendpoints.html
sidebar: sidebar
keywords: snapmirror,endpoint,endpoints,list,listing,listsnapmirrorendpoints
summary: 'The Element software web UI uses the ListSnapMirrorEndpoints method to list all SnapMirror endpoints that the Element storage cluster is communicating with.'
---

= ListSnapMirrorEndpoints
:icons: font
:imagesdir: ../media/

[.lead]
The Element software web UI uses the `ListSnapMirrorEndpoints` method to list all SnapMirror endpoints that the Element storage cluster is communicating with.

== Parameter

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
snapMirrorEndpointIDs
a|
Return only the objects associated with these IDs. If no IDs are provided or the array is empty, the method returns all SnapMirror endpoint IDs.
a|
integer array
a|
None
a|
No
|===

== Return value

This method has the following return value:

|===
|Name |Description |Type
a|
snapMirrorEndpoints
a|
A list of existing SnapMirror endpoints.
a|
xref:reference_element_api_snapmirrorendpoint.adoc[snapMirrorEndpoint] array
|===

== New since version

10.0
