---
permalink: api/reference_element_api_listvirtualvolumebindings.html
sidebar: sidebar
keywords: virtual,volume,vvol,cluster,bound,protocol,endpoint,binding,bindings,list,listing,listvirtualvolumebindings
summary: 'You can use the ListVirtualVolumeBindings method to get a list of all virtual volumes in the cluster that are bound to protocol endpoints.'
---

= ListVirtualVolumeBindings
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ListVirtualVolumeBindings` method to get a list of all virtual volumes in the cluster that are bound to protocol endpoints.

== Parameters

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
virtualVolumeBindingIDs
a|
A list of virtual volume binding IDs for which to retrieve information. If you omit this parameter, the method returns information about all virtual volume bindings.
a|
integer array
a|
None
a|
No
|===

== Return value

This method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
bindings
a|
A list of objects describing all virtual volumes in the cluster that are bound to protocol endpoints.
a|
xref:reference_element_api_binding_vvols.adoc[binding]
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "method": "ListVirtualVolumeBindings",
    "params": {
    },
    "id": 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 1,
  "result": {
    "bindings": [
      {
        "protocolEndpointID": "5dd53da0-b9b7-43f9-9b7e-b41c2558e92b",
        "protocolEndpointInBandID": "naa.6f47acc2000000016a67746700000000",
        "protocolEndpointType": "SCSI",
        "virtualVolumeBindingID": 177,
        "virtualVolumeHostID": "564de1a4-9a99-da0f-8b7c-3a41dfd64bf1",
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeSecondaryID": "0xe200000000a6"
      }
    ]
  }
}
----

== New since version

9.6
