---
permalink: api/reference_element_api_testping.html
sidebar: sidebar
keywords: ping,test,TestPing
summary: 'You can use the TestPing method to test network connectivity to all nodes in the cluster on both 1G and 10G interfaces using ICMP packets. The test uses the appropriate MTU sizes for each packet based on the MTU settings in the network configuration. TestPing does not create a temporary VLAN interface.'
---

= TestPing
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `TestPing` method to test network connectivity to all nodes in the cluster on both 1G and 10G interfaces using ICMP packets. The test uses the appropriate MTU sizes for each packet based on the MTU settings in the network configuration. `TestPing` does not create a temporary VLAN interface.

== Parameters

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
attempts
a|
Specifies the number of times the system should repeat the test ping.
a|
integer
a|
5
a|
No
a|
hosts
a|
Specifies a comma-separated list of addresses or hostnames of devices to ping. If no hosts are specified, the method pings the hosts in the storage cluster.
a|
string
a|
None
a|
No
a|
interface
a|
The existing (base) interface from which the pings should be sent. Possible values:

* `Bond10G`: Send pings from the Bond10G interface.
* `Bond1G`: Send pings from the Bond1G interface.

a|
string
a|
None
a|
No
a|
packetSize
a|
Specifies the number of bytes to send in the ICMP packet that is sent to each IP. The number of bytes must be less than the maximum MTU specified in the network configuration.
a|
integer
a|
None
a|
No
a|
pingTimeoutMsec
a|
Specifies the number of milliseconds to wait for each individual ping response.
a|
integer
a|
500 milliseconds
a|
No
a|
prohibitFragmentation
a|
Enables the DF (Do not Fragment) flag for the ICMP packets.
a|
boolean
a|
false
a|
No
a|
sourceAddressV4
a|
The source IPv4 address to use in the ICMP ping packets.
a|
string
a|
None
a|
No
a|
sourceAddressV6
a|
The source IPv6 address to use in the ICMP ping packets.
a|
string
a|
None
a|
No
a|
totalTimeoutSec
a|
Specifies the time in seconds the ping should wait for a system response before issuing the next ping attempt or ending the process.
a|
integer
a|
5
a|
No
a|
virtualNetworkTag
a|
The VLAN ID to use when sending the ping packets.
a|
integer
a|
None
a|
No
|===

== Return value

This method has the following return value:

|===
|Name |Description |Type
a|
details
a|
List of each IP the node was able to communicate with and ping response statistics.
a|
JSON object
|===

== Request example

Requests for this method are similar to the following example:

----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----

== New since version

5.0
