---
permalink: api/reference_element_api_getsnmptrapinfo.html
sidebar: sidebar
keywords: snmp,trap,get,getting,info,getsnmptrapinfo
summary: 'You can use the GetSnmpTrapInfo method to get current SNMP trap configuration information.'
---

= GetSnmpTrapInfo
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `GetSnmpTrapInfo` method to get current SNMP trap configuration information.

== Parameters

This method has no input parameters.

== Return values

This method has the following return values:

[options="header"]
|===
|Name |Description |Type
a|
trapRecipients
a|
List of hosts that are to receive the traps generated by the cluster.
a|
xref:reference_element_api_snmptraprecipient.adoc[snmpTrapRecipient] array
a|
clusterFaultTrapsEnabled
a|
The value true indicates that a solidFireClusterFaultNotification is configured to be sent to the list of trap recipients when a cluster fault is logged.
a|
boolean
a|
clusterFaultResolvedTrapsEnabled
a|
The value true indicates that a solidFireClusterFaultResolvedNotification is configured to be sent to the list of trap recipients when a cluster fault is resolved.
a|
boolean
a|
clusterEventTrapsEnabled
a|
The value true indicates that a solidFireClusterEventNotification is configured to be sent to the list of trap recipients when a cluster event is logged.
a|
boolean
|===

== Request example

Requests for this method are similar to the following example:

----
{
   "method":"GetSnmpTrapInfo"
   "params":{},
   "id":1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 1,
  "result": {
    "clusterEventTrapsEnabled": true,
    "clusterFaultResolvedTrapsEnabled": true,
    "clusterFaultTrapsEnabled": true,
    "trapRecipients": [
     {
      "community": "public",
      "host": "192.168.151.60",
      "port": 162
     },
     {
      "community": "solidfireAlerts",
      "host": "NetworkMonitor",
      "port": 162
     },
     {
      "community": "wakeup",
      "host": "PhoneHomeAlerter",
      "port": 1008
     }
   ]
 }
}
----

== New since version

9.6
