---
permalink: api/reference_element_api_listvolumestatsbyvolume.html
sidebar: sidebar
keywords: volumes,volume,stats,list,listing,listvolumestatsbyvolume,activity
summary: 'You can use the ListVolumeStatsByVolume method to list high-level activity measurements for every volume, by volume. Values are cumulative from the creation of the volume.'
---

= ListVolumeStatsByVolume
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ListVolumeStatsByVolume` method to list high-level activity measurements for every volume, by volume. Values are cumulative from the creation of the volume.

== Parameter

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
includeVirtualVolumes
a|
Virtual volumes are included in the response by default. To exclude virtual volumes, set to false.
a|
boolean
a|
true
a|
No
|===

== Return value

This method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
volumeStats
a|
List of volume activity information.
a|
xref:reference_element_api_volumestats.adoc[volumeStats] array
|===

== Request example

Requests for this method are similar to the following example:

----
{
   "method": "ListVolumeStatsByVolume",
   "params": {},
   "id" : 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 3,
        "actualIOPS": 0,
        "asyncDelay": null,
        "averageIOPSize": 4096,
        "burstIOPSCredit": 30000,
        "clientQueueDepth": 0,
        "desiredMetadataHosts": null,
        "latencyUSec": 0,
        "metadataHosts": {
          "deadSecondaries": [],
          "liveSecondaries": [
              16
          ],
          "primary": 12
        },
        "nonZeroBlocks": 7499205,
        "readBytes": 159012818944,
        "readBytesLastSample": 0,
        "readLatencyUSec": 0,
        "readOps": 38821489,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "throttle": 0,
        "timestamp": "2016-10-17T20:55:31.087537Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
          1
        ],
        "volumeID": 1,
        "volumeSize": 53687091200,
        "volumeUtilization": 0,
        "writeBytes": 52992585728,
        "writeBytesLastSample": 0,
        "writeLatencyUSec": 0,
        "writeOps": 12937643,
        "writeOpsLastSample": 0,
        "zeroBlocks": 5607995
      }
    ]
  }
}
----

== New since version

9.6
