---
permalink: api/reference_element_api_getnetworkinterface.html
sidebar: sidebar
keywords: nodes,node,network,interface,get,getting,getnetworkinterface
summary: 'You can use the GetNetworkInterface method to get information about a network interface on a node.'
---

= GetNetworkInterface
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `GetNetworkInterface` method to get information about a network interface on a node.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
interface
a|
The name of the interface to get information about for each node. Possible values:

* Bond1G
* Bond10G

a|
string
a|
None
a|
No
a|
force
a|
Set this parameter to true to run on all nodes in the cluster.
a|
boolean
a|
false
a|
No
|===

== Return value

This method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
nodes
a|
An array of objects describing the interface for each storage node in the storage cluster. Each object within the array contains the following items:

* nodeID: (integer) The ID of the storage node in the storage cluster the interface information applies to.
* result: (xref:reference_element_api_networkinterface.adoc[networkInterface]) Interface configuration information for this storage node.

a|
JSON object array
|===

== Request example

Requests for this method are similar to the following example:

----
{
	"method": "GetNetworkInterface",
	"params": {
		"interface": "Bond1G",
		"force": true
		},
	"id": 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
	"id": 1,
	"result": {
		"nodes": [
			{
				"nodeID": 1,
				"result": {
					"interface": {
						"address": "10.117.64.32",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "90:b1:1c:42:e0:1e",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 2,
				"result": {
					"interface": {
						"address": "10.117.64.35",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "d4:ae:52:7a:ae:23",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 3,
				"result": {
					"interface": {
						"address": "10.117.64.39",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "c8:1f:66:f0:9d:17",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			},
			{
				"nodeID": 4,
				"result": {
					"interface": {
						"address": "10.117.64.107",
						"addressV6": "::",
						"broadcast": "10.117.79.255",
						"macAddress": "b8:ca:3a:f5:24:f8",
						"mtu": 1500,
						"name": "Bond1G",
						"namespace": false,
						"netmask": "255.255.240.0",
						"status": "UpAndRunning",
						"type": "BondMaster",
						"virtualNetworkTag": 0
					}
				}
			}
		]
	}
}
----

== New since version

9.6
