---
permalink: api/reference_element_api_network_bonded_interfaces.html
sidebar: sidebar
keywords: object,objects,network
summary: 'The network \(bonded interfaces\) object contains configuration information for bonded network interfaces on a storage node. You can use the GetConfig and GetNetworkConfig methods to obtain this information for a storage node.'
---

= network (bonded interfaces)
:icons: font
:imagesdir: ../media/

[.lead]
The network (bonded interfaces) object contains configuration information for bonded network interfaces on a storage node. You can use the `GetConfig` and `GetNetworkConfig` methods to obtain this information for a storage node.

== Object members

This object contains the following members:

|===
|Name |Description |Type
a|
address
a|
The IPv4 address assigned to this interface on the node.
a|
string
a|
addressV6
a|
The IPv6 management address assigned to the Bond1G interface on the node.
a|
string
a|
bond-downdelay
a|
Time to wait, in milliseconds, before disabling a slave after a link failure has been detected.
a|
string
a|
bond-fail_over_mac
a|
The configuration of the MAC address of the network interface.
a|
string
a|
bond-miimon
a|
The frequency, in milliseconds, at which the MII link state is inspected for link failures.
a|
string
a|
bond-mode
a|
The bonding mode. Possible values:

* ActivePassive (Default)
* ALB
* LACP (Recommended)

a|
string
a|
bond-primary_reselect
a|
Specifies when the primary bond slave is chosen as the active slave. Possible values:

* Always
* Better
* Failure

a|
string
a|
bond-slaves
a|
The list of slave interfaces for the bond.
a|
string
a|
bond-lacp_rate
a|
When Bond Mode is LACP, the rate may change to one of the following:

* LACP Fast (Default)
* LACP Slow

a|
string
a|
bond-updelay
a|
The time, in milliseconds, to wait before enabling a slave after a link is detected.
a|
string
a|
dns-nameservers
a|
A list of addresses used for domain name services, separated by comma or space.
a|
string
a|
dns-search
a|
A space or comma separated list of DNS search domains.
a|
string
a|
family
a|
Address family that the interface is configured to use. Currently "inet" for IPv4 is supported.
a|
string
a|
gateway
a|
The IPv4 router network address used to send traffic from the local network.
a|
string
a|
gatewayV6
a|
The IPv6 router network address used to send traffic from the local Bond1G network.
a|
string
a|
ipV6PrefixLength
a|
The subnet prefix length for static routes of type "net" for IPv6 traffic on the Bond1G network.
a|
string
a|
macAddress
a|
The actual MAC address assigned to the interface and observed by the network.
a|
string
a|
macAddressPermanent
a|
The immutable MAC address assigned by the manufacturer to the interface.
a|
string
a|
method
a|
The method used to configure the interface. Possible values:

* Loopback: Used to define the IPv4 loopback interface.
* manual: Used to define interfaces that are not configured automatically.
* dhcp: Can be used to obtain an IP address via DHCP.
* static: Used to define Ethernet interfaces with statically allocated IPv4 addresses.

a|
string
a|
mtu
a|
The largest packet size (in bytes) that the interface can transmit. Must be greater than or equal to 1500; up to 9000 is supported.
a|
string
a|
netmask
a|
The bitmask that specifies the subnet for the interface.
a|
string
a|
network
a|
Indicates where the IP address range begins based on the netmask.
a|
string
a|
routes
a|
Comma separated array of route strings to apply to the routing table.
a|
string array
a|
status
a|
The state of the interface. Possible values:

* Down: The interface is inactive.
* Up: The interface is ready, but has no link.
* UpAndRunning: The interface is ready and a link is established.

a|
string
a|
symmetricRouteRules
a|
The symmetric routing rules configured on the node.
a|
string array
a|
upAndRunning
a|
Indicates if the interface is ready and has a link.
a|
boolean
a|
virtualNetworkTag
a|
The virtual network identifier of the interface (VLAN tag).
a|
string
|===

== Member modifiability and node states

This table indicates whether or not the object parameters can be modified at each possible node state.

|===
| Member name| Available state| Pending state| Active state
a|
address
a|
Yes
a|
Yes
a|
No
a|
addressV6
a|
Yes
a|
Yes
a|
No
a|
bond-downdelay
a|
Configured by the system
a|
N/A
a|
N/A
a|
bond-fail_over_mac
a|
Configured by the system
a|
N/A
a|
N/A
a|
bond-miimon
a|
Configured by the system
a|
N/A
a|
N/A
a|
bond-mode
a|
Yes
a|
Yes
a|
Yes
a|
bond-primary_reselect
a|
Configured by the system
a|
N/A
a|
N/A
a|
bond-slaves
a|
Configured by the system
a|
N/A
a|
N/A
a|
bond-lacp_rate
a|
Yes
a|
Yes
a|
Yes
a|
bond-updelay
a|
Configured by the system
a|
N/A
a|
N/A
a|
dns-nameservers
a|
Yes
a|
Yes
a|
Yes
a|
dns-search
a|
Yes
a|
Yes
a|
Yes
a|
family
a|
No
a|
No
a|
No
a|
gateway
a|
Yes
a|
Yes
a|
Yes
a|
gatewayV6
a|
Yes
a|
Yes
a|
Yes
a|
ipV6PrefixLength
a|
Yes
a|
Yes
a|
Yes
a|
macAddress
a|
Configured by the system
a|
N/A
a|
N/A
a|
macAddressPermanent
a|
Configured by the system
a|
N/A
a|
N/A
a|
method
a|
No
a|
No
a|
No
a|
mtu
a|
Yes
a|
Yes
a|
Yes
a|
netmask
a|
Yes
a|
Yes
a|
Yes
a|
network
a|
No
a|
No
a|
No
a|
routes
a|
Yes
a|
Yes
a|
Yes
a|
status
a|
Yes
a|
Yes
a|
Yes
a|
symmetricRouteRules
a|
Configured by the system
a|
N/A
a|
N/A
a|
upAndRunning
a|
Configured by the system
a|
N/A
a|
N/A
a|
virtualNetworkTag
a|
Yes
a|
Yes
a|
Yes
|===


== Find more information

* xref:reference_element_api_getconfig.adoc[GetConfig]
* xref:reference_element_api_getnetworkconfig.adoc[GetNetworkConfig]
