---
permalink: api/reference_element_api_clusterstats.html
sidebar: sidebar
keywords: objects,clusterStats
summary: 'The clusterStats object contains statistical data for a cluster. Many of the volume-related statistics contained in the object are averaged for all volumes in the cluster. You can use the GetClusterStats method to retrieve this information for a cluster.'
---

= clusterStats
:icons: font
:imagesdir: ../media/

[.lead]
The clusterStats object contains statistical data for a cluster. Many of the volume-related statistics contained in the object are averaged for all volumes in the cluster. You can use the GetClusterStats method to retrieve this information for a cluster.

== Object members

This object contains the following members:

[options="header"]
|===
|Name |Description |Calculation |Type
a|
actualIOPS
a|
Current actual IOPS for the entire cluster in the last 500 milliseconds.
a|
Point in time
a|
integer
a|
averageIOPSize
a|
Average size in bytes of recent I/O to the cluster in the last 500 milliseconds.
a|
Point in time
a|
integer
a|
clientQueueDepth
a|
The number of outstanding read and write operations to the cluster.
a|
N/A
a|
integer
a|
clusterUtilization
a|
The percentage of the cluster's max IOPS currently being utilized. This is computed as clusterUtilization = normalizedIOPS / maxIOPS (from GetClusterCapacity).
a|
N/A
a|
float
a|
latencyUSec
a|
The average time, in microseconds, to complete operations to a cluster in the last 500 milliseconds.
a|
Point in time
a|
integer
a|
normalizedIOPS
a|
Average number of IOPS for the entire cluster in the last 500 milliseconds.
a|
Point in time
a|
integer
a|
readBytes
a|
The total cumulative bytes read from the cluster since the creation of the cluster.
a|
Monotonically increasing
a|
integer
a|
readBytesLastSample
a|
The total number of bytes read from the cluster during the last sample period.
a|
Point in time
a|
integer
a|
readLatencyUSec
a|
The average time, in microseconds, to complete read operations to the cluster in the last 500 milliseconds.
a|
Point in time
a|
integer
a|
readLatencyUSecTotal
a|
The total time spent performing read operations since the creation of the cluster.
a|
Monotonically increasing
a|
integer
a|
readOps
a|
The total cumulative read operations to the cluster since the creation of the cluster.
a|
Monotonically increasing
a|
integer
a|
readOpsLastSample
a|
The total number of read operations during the last sample period.
a|
Point in time
a|
integer
a|
samplePeriodMSec
a|
The length of the sample period, in milliseconds.
a|
N/A
a|
integer
a|
servicesCount
a|
The number of services running on the cluster. If equal to the servicesTotal, this indicates that valid statistics were collected from all nodes.
a|
Point in time
a|
integer
a|
servicesTotal
a|
The total number of expected services running on the cluster.
a|
N/A
a|
integer
a|
timestamp
a|
The current time in UTC+0 format.
a|
N/A
a|
ISO 8601 date string
a|
unalignedReads
a|
The total cumulative unaligned read operations to a cluster since the creation of the cluster.
a|
Monotonically increasing
a|
integer
a|
unalignedWrites
a|
The total cumulative unaligned write operations to a cluster since the creation of the cluster.
a|
Monotonically increasing
a|
integer
a|
writeBytes
a|
The total cumulative bytes written to the cluster since the creation of the cluster.
a|
Monotonically increasing
a|
integer
a|
writeBytesLastSample
a|
The total number of bytes written to the cluster during the last sample period.
a|
Monotonically increasing
a|
integer
a|
writeLatencyUSec
a|
The average time, in microseconds, to complete write operations to a cluster in the last 500 milliseconds.
a|
Point in time
a|
integer
a|
writeLatencyUSecTotal
a|
The total time spent performing write operations since the creation of the cluster.
a|
Monotonically increasing
a|
integer
a|
writeOps
a|
The total cumulative write operations to the cluster since the creation of the cluster.
a|
Monotonically increasing
a|
integer
a|
writeOpsLastSample
a|
The total number of write operations during the last sample period.
a|
Point in time
a|
integer
|===

== Find more information

xref:reference_element_api_getclusterstats.adoc[GetClusterStats]
