---
permalink: api/reference_element_api_listclusterpairs.html
sidebar: sidebar
keywords: cluster,pair,pairs,paired,list,listing,listclusterpairs
summary: 'You can use the ListClusterPairs method to list all clusters that are paired with the current cluster. This method returns information about active and pending cluster pairings, such as statistics about the current pairing as well as the connectivity and latency \(in milliseconds\) of the cluster pairing.'
---

= ListClusterPairs
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ListClusterPairs` method to list all clusters that are paired with the current cluster. This method returns information about active and pending cluster pairings, such as statistics about the current pairing as well as the connectivity and latency (in milliseconds) of the cluster pairing.

== Parameter

This method has no input parameter:

== Return value

This method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
clusterPairs
a|
Information about each paired cluster.
a|
xref:reference_element_api_clusterpair.adoc[clusterPair] array
|===

== Request example

Requests for this method are similar to the following example:

----
{
   "method": "ListClusterPairs",
   "params": {
      },
   "id" : 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
 "id": 1,
 "result": {
   "clusterPairs": [
     {
      "clusterName": "cluster2",
      "clusterPairID": 3,
      "clusterPairUUID": "9866fbeb-c2f8-4df3-beb9-58a5c4e49c9b",
      "clusterUUID": 5487,
      "latency": 1,
      "mvip": "172.1.1.5",
      "status": "Connected"
      "version": "8.0.0.1361"
     },
     {
      "clusterName": "cluster3",
      "clusterPairID": 2,
      "clusterPairUUID": "8132a699-ce82-41e0-b406-fb914f976042",
      "clusterUUID": 1383,
      "latency": 1,
      "mvip": "172.1.1.6",
      "status": "Connected"
      "version": "8.0.0.1361"
     }
   ]
 }
----

== New since version

9.6
