---
permalink: api/reference_element_api_protectionschemeresiliency.html
sidebar: sidebar
keywords: object,objects,protectionSchemeResiliency
summary: 'The protectionSchemeResiliency object contains information about whether a storage cluster, for a specific protection scheme, can automatically heal itself from one or more failures within its associated protectionDomainType. A storage cluster is considered healed when it can continue reading and writing data through the failure of any single storage node \(a state known as node tolerance\).'
---

= protectionSchemeResiliency
:icons: font
:imagesdir: ../media/

[.lead]
The protectionSchemeResiliency object contains information about whether a storage cluster, for a specific protection scheme, can automatically heal itself from one or more failures within its associated protectionDomainType. A storage cluster is considered healed when it can continue reading and writing data through the failure of any single storage node (a state known as node tolerance).

== Object members

This object contains the following members:

[options="header"]
|===
|Name |Description |Type
a|
protectionScheme
a|
The current protection scheme of this storage cluster. The only possible value is doubleHelix.
a|
string
a|
sustainableFailuresForBlockData
a|
The predicted number of simultaneous failures which can occur without losing the ability to automatically heal to a state of node tolerance for data.
a|
integer
a|
sustainableFailuresForMetadata
a|
The predicted number of simultaneous failures which can occur without losing the ability to automatically heal to a state of node tolerance for metadata.
a|
integer
|===
