---
permalink: api/reference_element_api_copyvolume.html
sidebar: sidebar
keywords: volume,volumes,CopyVolume,overwrite,overwriting,data
summary: 'You can use the CopyVolume method to overwrite the data contents of an existing volume with the data contents of another volume \(or snapshot\). Attributes of the destination volume such as IQN, QoS settings, size, account, and volume access group membership are not changed. The destination volume must already exist and must be the same size as the source volume.'
---

= CopyVolume
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `CopyVolume` method to overwrite the data contents of an existing volume with the data contents of another volume (or snapshot). Attributes of the destination volume such as IQN, QoS settings, size, account, and volume access group membership are not changed. The destination volume must already exist and must be the same size as the source volume.

It is best if clients unmount the destination volume before the operation begins. If the destination volume is modified during the operation, the changes are lost. This operation can take a variable amount of time to complete. You can use the xref:reference_element_api_getasyncresult.adoc[GetAsyncResult] method to determine when the process has finished, and xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs] to see the progress of the copy.

== Parameters

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
dstVolumeID
a|
VolumeID of the volume to overwrite.
a|
integer
a|
None
a|
Yes
a|
volumeID
a|
VolumeID of the volume to be read from.
a|
integer
a|
None
a|
Yes
a|
snapshotID
a|
ID of the snapshot that is used as the source of the clone. If no ID is provided, the current active volume is used.
a|
integer
a|
None
a|
No
|===

== Return values

This method has the following return values:

|===
|Name |Description |Type
a|
asyncHandle
a|
Handle value used to obtain the operation result.
a|
integer
a|
cloneID
a|
CloneID for the newly cloned volume.
a|
integer
|===

== Request example

Requests for this method are similar to the following example:

----
{
   "method": "CopyVolume",
   "params": {
      "volumeID" : 3,
      "dstVolumeID" : 2
   },
   "id" : 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 1,
  "result": {
    "asyncHandle": 9,
    "cloneID": 5
  }
}
----

== New since version

9.6

== Find more information

* xref:reference_element_api_getasyncresult.adoc[GetAsyncResult]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]
