---
permalink: api/reference_element_api_secureerasedrives.html
sidebar: sidebar
keywords: drive,drives,secure,erase,reset,resetting,encryption,key,secureerasedrives
summary: 'You can use the SecureEraseDrives method to remove any residual data from drives that have a status of "available". You might use this method when replacing a drive nearing the end of its service life that contained sensitive data. This method uses a Security Erase Unit command to write a predetermined pattern to the drive and resets the encryption key on the drive. This asynchronous method might take several minutes to complete.'
---

= SecureEraseDrives
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `SecureEraseDrives` method to remove any residual data from drives that have a status of "available". You might use this method when replacing a drive nearing the end of its service life that contained sensitive data. This method uses a Security Erase Unit command to write a predetermined pattern to the drive and resets the encryption key on the drive. This asynchronous method might take several minutes to complete.

== Parameter

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
drives
a|
List of drive IDs to secure erase.
a|
integer array
a|
None
a|
Yes
|===

== Return value

This method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
asyncHandle
a|
Handle value used to obtain the operation result.
a|
integer
|===

== Request example

Requests for this method are similar to the following example:

----
{
   "method": "SecureEraseDrives",
   "params": {
     "drives"  : [3, 4, 5]
   },
   "id" : 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
   "id" : 1
   "result" : {
     "asyncHandle" : 1
   }
}
----

== New since version

9.6

== Find more information

* xref:reference_element_api_getasyncresult.adoc[GetAsyncResult]
* xref:reference_element_api_listdrives.adoc[ListDrives]
