---
permalink: api/reference_element_api_listprotocolendpoints.html
sidebar: sidebar
keywords: protocol,endpoints,endpoint,list,listing,listprotocolendpoints
summary: 'You can use the ListProtocolEndpoints method to retrieve information about all protocol endpoints in the cluster. Protocol endpoints govern access to their associated virtual volume storage containers.'
---

= ListProtocolEndpoints
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ListProtocolEndpoints` method to retrieve information about all protocol endpoints in the cluster. Protocol endpoints govern access to their associated virtual volume storage containers.

== Parameters

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
protocolEndpointIDs
a|
A list of protocol endpoint IDs for which to retrieve information. If you omit this parameter, the method returns information about all protocol endpoints.
a|
protocolEndpointID UUID array
a|
None
a|
No
|===

== Return values

This method has the following return value:

[options="header"]
|===
|Name |Description |Type
a|
protocolEndpoints
a|
List of objects containing information about each protocol endpoint in the system.
a|
xref:reference_element_api_protocolendpoint.adoc[protocolEndpoint] array
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "id": 1,
  "method": "ListProtocolEndpoints",
  "params": {}
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 1,
  "result": {
    "protocolEndpoints": [
      {
        "primaryProviderID": 1,
        "protocolEndpointID": "1387e257-d2e3-4446-be6d-39db71583e7b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000016970687200000000",
        "secondaryProviderID": 2
      },
      {
        "primaryProviderID": 2,
        "protocolEndpointID": "1f16ed86-3f31-4c76-b004-a1251187700b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000026970687200000000",
        "secondaryProviderID": 3
      },
      {
        "primaryProviderID": 4,
        "protocolEndpointID": "c6458dfe-9803-4350-bb4e-68a3feb7e830",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000046970687200000000",
        "secondaryProviderID": 1
      },
      {
        "primaryProviderID": 3,
        "protocolEndpointID": "f3e7911d-0e86-4776-97db-7468c272213f",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000036970687200000000",
        "secondaryProviderID": 4
      }
    ]
  }
}
----

== New since version

9.6
