---
permalink: api/reference_element_api_setloginbanner.html
sidebar: sidebar
keywords: terms,use,banner,configure,set,setting,setloginbanner,login
summary: 'You can use the SetLoginBanner method to configure the Terms of Use banner that users see when they log in to the Element web interface.'
---

= SetLoginBanner
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `SetLoginBanner` method to configure the Terms of Use banner that users see when they log in to the Element web interface.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
banner
a|
The desired text of the Terms of Use banner. The maximum length allowed is 4,096 characters.
a|
string
a|
None
a|
No
a|
enabled
a|
The status of the Terms of Use banner. Possible values:

* `true`: The Terms of Use banner is displayed upon web interface login.
* `false`: The Terms of Use banner is not displayed upon web interface login.

a|
boolean
a|
None
a|
No
|===

== Return values

This method has the following return values:

[options="header"]
|===
|Name |Description |Type
a|
banner
a|
The current text of the Terms of Use banner. This value can contain text even when the banner is disabled.
a|
string
a|
enabled
a|
The status of the Terms of Use banner. Possible values:

* true: The Terms of Use banner is displayed upon web interface login.
* false: The Terms of Use banner is not displayed upon web interface login.

a|
boolean
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "id": 3920,
  "method": "SetLoginBanner",
  "params": {
    "banner": "Welcome to NetApp!",
    "enabled": true
  }
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 3920,
  "result": {
    "loginBanner": {
      "banner": "Welcome to NetApp!",
      "enabled": true
    }
  }
}
----

== New since version

10.0
