---
permalink: api/reference_element_api_disablemaintenancemode.html
sidebar: sidebar
keywords: disable,maintenance,mode
summary: 'You can use the DisableMaintenanceMode method to take a storage node out of maintenance mode. You should only disable maintenance mode after you have completed maintenance and the node is online.'
---

= DisableMaintenanceMode
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `DisableMaintenanceMode` method to take a storage node out of maintenance mode. You should only disable maintenance mode after you have completed maintenance and the node is online.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
nodes
a|
List of storage node IDs to take out of maintenance mode.
a|
integer array
a|
None
a|
Yes
|===

== Return values

This method has the following return values:

|===
|Name |Description |Type
a|
asyncHandle
a|
You can use the GetAsyncResult method to retrieve this asyncHandle and determine when the maintenance mode transition is complete.
a|
integer
a|
currentMode
a|
The current maintenance mode state of the node. Possible values:

* Disabled: No maintenance has been requested.
* FailedToRecover: The node failed to recover from maintenance mode.
* Unexpected: The node was found to be offline, but was in the Disabled mode.
* RecoveringFromMaintenance: The node is in the process of recovering from maintenance mode.
* PreparingForMaintenance: Actions are being taken to prepare a node to have maintenance performed.
* ReadyForMaintenance: The node is ready for maintenance to be performed.

a|
MaintenanceMode (string)
a|
requestedMode
a|
The requested maintenance mode state of the node. Possible values:

* Disabled: No maintenance has been requested.
* FailedToRecover: The node failed to recover from maintenance mode.
* Unexpected: The node was found to be offline, but was in the Disabled mode.
* RecoveringFromMaintenance: The node is in the process of recovering from maintenance mode.
* PreparingForMaintenance: Actions are being taken to prepare a node to have maintenance performed.
* ReadyForMaintenance: The node is ready for maintenance to be performed.

a|
MaintenanceMode (string)
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "method": "DisableMaintenanceMode",
  "params": {
    "nodes": [6]
  },
"id": 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
   "id": 1,
   "result":
      {
        "requestedMode": "Disabled",
        "asyncHandle": 1,
        "currentMode": "Enabled"
    }
}
----

== New since version

12.2

== Find more information

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html[NetApp HCI storage maintenance mode concepts^]
