---
permalink: api/reference_element_api_listsnapmirrorvservers.html
sidebar: sidebar
keywords: snapmirror,vserver,vservers,list,listing,listsnapmirrorvservers
summary: 'The Element software web UI uses the ListSnapMirrorVservers method to list all SnapMirror Vservers available on a remote ONTAP system.'
---

= ListSnapMirrorVservers
:icons: font
:imagesdir: ../media/

[.lead]
The Element software web UI uses the `ListSnapMirrorVservers` method to list all SnapMirror Vservers available on a remote ONTAP system.

== Parameter

This method has the following input parameter:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
snapMirrorEndpointID
a|
List only the Vservers associated with the specified endpoint ID. If no endpoint ID is provided, the system lists Vservers from all known SnapMirror endpoints.
a|
integer
a|
None
a|
No
a|
vserverType
a|
List only Vservers of the specified type. Possible values:

* admin
* data
* node
* system

a|
string
a|
None
a|
No
a|
vserverName
a|
List only Vservers with the specified name.
a|
string
a|
None
a|
No
|===

== Return value

This method has the following return value:

|===
|Name |Description |Type
a|
snapMirrorVservers
a|
A list of the SnapMirror Vservers available on the ONTAP storage system.
a|
xref:reference_element_api_snapmirrorvserver.adoc[snapMirrorVserver] array
|===

== New since version

10.1
