---
permalink: api/reference_element_api_setsnmptrapinfo.html
sidebar: sidebar
keywords: snmp,trap,information,info,setting,set,setsnmptrapinfo
summary: 'You can use the SetSnmpTrapInfo method to enable and disable the generation of cluster SNMP notifications \(traps\) and to specify the set of hosts that receive the notifications. The values you pass with each SetSnmpTrapInfo method call replace all values set in any previous call.'
---

= SetSnmpTrapInfo
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `SetSnmpTrapInfo` method to enable and disable the generation of cluster SNMP notifications (traps) and to specify the set of hosts that receive the notifications. The values you pass with each `SetSnmpTrapInfo` method call replace all values set in any previous call.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type
a|
trapRecipients
a|
List of hosts that are to receive the traps generated by the storage cluster. At least one object is required if any one of the trap types is enabled. This parameter is required only if any boolean parameters are set to true. (No default value. Not required.)
a|
xref:reference_element_api_snmptraprecipient.adoc[snmpTrapRecipient] array
a|
clusterFaultTrapsEnabled
a|
If set to true, a corresponding cluster fault notification is sent to the configured list of trap recipients when a cluster fault is logged. (Default value: false. Not required.)
a|
boolean
a|
clusterFaultResolvedTrapsEnabled
a|
If set to true, a corresponding cluster fault resolved notification is sent to the configured list of trap recipients when a cluster fault is resolved. (Default value: false. Not required.)
a|
boolean
a|
clusterEventTrapsEnabled
a|
If set to true, a corresponding cluster event notification is sent to the configured list of trap recipients when a cluster event is logged. (Default value: false. Not required.)
a|
boolean
|===

== Return values

This method has no return values.

== Request example

Requests for this method are similar to the following example:

----
{
"method":"SetSnmpTrapInfo",
"params":{
    "clusterFaultTrapsEnabled":true,
    "clusterFaultResolvedTrapsEnabled":true,
    "clusterEventTrapsEnabled":true,
    "trapRecipients":[
    {
      "host":"192.30.0.10",
      "port":162,
      "community":"public"
    }
   ]
  },
  "id":1
}
----

== Response example

This method returns a response similar to the following example:

----
{
    "id" : 1,
    "result" : {}
}
----

== New since version

9.6
