---
permalink: api/reference_element_api_listvolumes.html
sidebar: sidebar
keywords: volume,volumes,list,listing,listvolumes
summary: 'You can use the ListVolumes method to get a list of volumes that are in a cluster. You can specify the volumes you want to return in the list by using the available parameters.'
---

= ListVolumes
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ListVolumes` method to get a list of volumes that are in a cluster. You can specify the volumes you want to return in the list by using the available parameters.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
accounts
a|
Only volumes owned by the accounts you specify here are returned. Mutually exclusive with the volumeIDs parameter.
a|
integer array
a|
None
a|
No
a|
includeVirtualVolumes
a|
Virtual volumes are included in the response by default. To exclude virtual volumes, set to false.
a|
boolean
a|
true
a|
No
a|
isPaired
a|
Returns volumes that are paired or not paired. Possible values:

* true: Returns all paired volumes.
* false: Returns all volumes not paired.

a|
boolean
a|
None
a|
No
a|
limit
a|
Enables you to set the maximum number of volume results that are returned. Mutually exclusive with the volumeIDs parameter.
a|
integer
a|
10000
a|
No
a|
startVolumeID
a|
Only volumes with an ID greater than or equal to this value are returned. Mutually exclusive with the volumeIDs parameter.
a|
integer
a|
None
a|
No
a|
volumeIDs
a|
A list of volume IDs. If you specify this parameter, other parameters operate only on this set of volumes. Mutually exclusive with the accounts, startVolumeID, and limit parameters.
a|
integer array
a|
No
a|
No
a|
volumeName
a|
Only volume object information matching the volume name is returned.
a|
string
a|
No
a|
No
a|
volumeStatus
a|
Only volumes with a status equal to the status value are returned. Possible values:

* creating
* snapshotting
* active
* deleted

a|
string
a|
No
a|
No
|===

== Return value

This method has the following return value:

|===
|Name |Description |Type
a|
volumes
a|
List of volumes.
a|
xref:reference_element_api_volume.adoc[volume] array
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----

== New since version

9.6
