---
permalink: api/reference_element_api_snapshot.html
sidebar: sidebar
keywords: object,objects,snapshot
summary: 'The snapshot object contains information about a snapshot made for a volume. You can use the ListSnapshots API method to retrieve a list of snapshot information for a volume or for all volumes. The object includes information about the active snapshot as well as each snapshot created for a volume.'
---

= snapshot
:icons: font
:imagesdir: ../media/

[.lead]
The snapshot object contains information about a snapshot made for a volume. You can use the `ListSnapshots` API method to retrieve a list of snapshot information for a volume or for all volumes. The object includes information about the active snapshot as well as each snapshot created for a volume.

== Object members

This object contains the following members:

[options="header"]
|===
|Name |Description |Type
a|
attributes
a|
List of name-value pairs in JSON object format.
a|
JSON object
a|
checksum
a|
A small string representation of the data in the stored snapshot. This checksum can be used later to compare other snapshots to detect errors in the data.
a|
string
a|
createTime
a|
The UTC+0 formatted time the snapshot was created.
a|
ISO 8601 date string
a|
enableRemoteReplication
a|
Identifies if snapshot is enabled for remote replication.
a|
boolean
a|
expirationReason
a|
Indicates how the snapshot expiration is set. Possible values:

* Api: The expiration time is set by using the API.
* None: No expiration time is set.
* Test: The expiration time is set for testing.
* fifo: Expiration occurs on a first-in-first-out basis.

a|
string
a|
expirationTime
a|
The time at which this snapshot will expire and be purged from the cluster.
a|
ISO 8601 date string
a|
groupID
a|
The group ID if the snapshot is a member of a group snapshot.
a|
integer
a|
groupsnapshotUUID
a|
Contains information about each snapshot in the group. Each of these members will have a UUID parameter for the snapshot's UUID.
a|
string
a|
instanceCreateTime
a|
The time that the snapshot was created on the local cluster.
a|
ISO 8601 date string
a|
instanceSnapshotUUID
a|
The universally unique ID of the snapshot on the local cluster. This ID does not get replicated to other clusters.
a|
string
a|
name
a|
The unique name assigned to the snapshot. If no name is specified, the name is the UTC+0 formatted timestamp of when the snapshot was created.
a|
string
a|
remoteStatuses
a|
An array containing the universal identifier and replication status of each remote snapshot on the target cluster as seen from the source cluster.
a|
xref:reference_element_api_remoteclustersnapshotstatus.adoc[remoteClusterSnapshotStatus] array
a|
snapMirrorLabel
a|
The label used by SnapMirror software to specify snapshot retention policy on SnapMirror endpoints. If not set, this value is null.
a|
string
a|
snapshotID
a|
The unique ID of an existing snapshot.
a|
string
a|
snapshotUUID
a|
The universally unique ID of an existing snapshot. When the snapshot is replicated across clusters, this ID is replicated along with it and is used to identify the snapshot across clusters.
a|
string
a|
status
a|
Current status of the snapshot. Possible values:

* Unknown: There was an error obtaining the status of the snapshot.
* Preparing: This snapshot is being prepared for use and is not yet writable.
* RemoteSyncing: This snapshot is being replicated from a remote cluster.
* Done: This snapshot has finished preparation or replication and is now usable.
* Active: This snapshot is the active branch.
* Cloning: This snapshot is involved in a CopyVolume operation.

a|
string
a|
totalSize
a|
The total size in bytes of the snapshot.
a|
integer
a|
virtualVolumeID
a|
The ID of the virtual volume associated with this snapshot.
a|
UUID
a|
volumeID
a|
The ID of the volume the snapshot was created from.
a|
integer
a|
volumeName
a|
The name of the volume at the time the snapshot was created.
a|
string
|===


== Find more information

xref:reference_element_api_listsnapshots.adoc[ListSnapshots]
