---
permalink: api/reference_element_api_modifyqospolicy.html
sidebar: sidebar
keywords: modify,modifying,edit,editing,change,changing,qos,policy,policies,modifyqospolicy
summary: 'You can use the ModifyQoSPolicy method to modify an existing QoS policy on the system.'
---

= ModifyQoSPolicy
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `ModifyQoSPolicy` method to modify an existing QoS policy on the system.

== Parameters

This method has the following input parameters:

|===
|Name |Description |Type |Default value |Required
a|
qosPolicyID
a|
The ID of the policy to be modified.
a|
integer
a|
None
a|
Yes
a|
name
a|
If supplied, the name of the QoS policy (e.g. gold, platinum, silver) is changed to this value.
a|
string
a|
None
a|
No
a|
qos
a|
If supplied, the QoS settings for this policy are changed to these settings. You can supply partial QoS values and only change some of the QoS settings.
a|
QoS object
a|
None
a|
No
|===

== Return values

This method has the following return values:

|===
|Name |Description |Type
a|
qosPolicy
a|
Details of the newly modified QoS policy.
a|
xref:reference_element_api_qospolicy.adoc[QoSPolicy]
|===

== Request example

Requests for this method are similar to the following example:

----
{
  "id": 1950,
  "method": "ModifyQoSPolicy",
  "params": {
    "qosPolicyID": 2,
    "qos": {
      "minIOPS": 51,
      "maxIOPS": 15002,
      "burstIOPS": 15002
    }
  }
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": 1950,
  "result": {
    "qosPolicy": {
      "name": "bronze",
      "qos": {
        "burstIOPS": 15002,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 15002,
        "minIOPS": 51
      },
      "qosPolicyID": 2,
      "volumeIDs": [
        2
      ]
    }
  }
}
----

== New since version

10.0
