---
permalink: api/reference_element_api_completevolumepairing.html
sidebar: sidebar
keywords: volume,pairing,CompleteVolumePairing,pair,volumes,complete,completing
summary: 'You can use CompleteVolumePairing to complete the pairing of two volumes.'
---

= CompleteVolumePairing
:icons: font
:imagesdir: ../media/

[.lead]
You can use `CompleteVolumePairing` to complete the pairing of two volumes.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
volumeID
a|
The ID of volume that will complete the volume pair.
a|
integer
a|
None
a|
Yes
a|
volumePairingKey
a|
The key returned from the xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing] API method.
a|
string
a|
None
a|
Yes
|===

== Return value

This method has no return values.

== Request example

Requests for this method are similar to the following example:

----
{
   "method": "CompleteVolumePairing",
   "params": {
        "volumeID" : 12,
        "volumePairingKey" : "7b22636c7573746572506169724944223a312c22636c75737465725061697255554944223a2231636561313336322d346338662d343631612d626537322d373435363661393533643266222c22636c7573746572556e697175654944223a2278736d36222c226d766970223a223139322e3136382e3133392e313232222c226e616d65223a224175746f54657374322d63307552222c2270617373776f7264223a22695e59686f20492d64774d7d4c67614b222c22727063436f6e6e656374696f6e4944223a3931333134323634392c22757365726e616d65223a225f5f53465f706169725f50597a796647704c7246564432444a42227d"
        },
   "id" : 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
"id": 1,
"result": {}
}
----

== New since version

9.6

== Find more information

xref:reference_element_api_startvolumepairing.adoc[StartVolumePairing]
