---
permalink: api/reference_element_api_signsshkeys.html
sidebar: sidebar
keywords: ssh, sign key
summary: 'After ssh is enabled on a node or cluster, you can use the SignSshKeys method to gain access to a shell on a node as either sfadmin or sfreadonly. sfreadonly is a new user account as of Element 12.5 that allows for initial troubleshooting on a node but lacks privileges to make elevated commands.'
---

= SignSshKeys
:icons: font
:imagesdir: ../media/

[.lead]
After SSH is enabled on the cluster using the link:../api/reference_element_api_enablessh.html[EnableSSH method], you can use the `SignSshKeys` method to gain access to a shell on a node.

Beginning with Element 12.5, `sfreadonly` is a new system account allows for basic troubleshooting on a node. This API enables SSH access using the `sfreadonly` system account across all nodes in the cluster.

WARNING: Unless advised by NetApp Support, any alterations to the system are unsupported, voiding your support contract, and may result in instability or inaccessibility of data.

After you use the method, you must copy the keychain from the response, save it to the system that will be initiating the SSH connection, then run the following command:

----
ssh -i <identity_file> sfreadonly@<node_ip>
----

`identity_file` is a file from which the identity (private key) for public key authentication is read and `node_ip` is the IP address of the node. For more information on `identity_file`, see the SSH man page.

== Parameters

This method has the following input parameters:

[options="header"]
|===
|Name |Description |Type |Default value |Required
a|
duration
a|
Integer from 1 to 24 reflecting number of hours for signed key to be valid. If duration is not specified, the default is used.
a|
integer
a|
1
a|
No
a|
publicKey
a|
If provided, this parameter will only return the signed_public_key instead of creating a full keychain to the user.

NOTE: Public keys submitted using the URL bar in a browser with `+` are interpreted as spaced and break signing.

a|
string
a|
Null
a|
No
a|
sfadmin
a|
Allows access to the sfadmin shell account when you make the API call with supportAdmin cluster access, or when the node is not in a cluster.
a|
boolean
a|
False
a|
No
|===

== Return values

This method has the following return values:

[options="header"]
|===
|Name |Description |Type
a|
keygen_status
a|
Contains the identity in the signed key, the principals allowed, and the valid start and end dates for the key.
a|
string
a|
private_key
a|
A private SSH key value is only returned if the API is generating a complete keychain for the end user.

NOTE: The value is Base64 encoded; you must decode the value when it is written to a file to ensure that it is read as a valid private key.

a|
string
a|
public_key
a|
A public SSH key value is only returned if the API is generating a complete keychain for the end user.

NOTE: When you pass a public_key parameter to the API method, only the `signed_public_key` value is returned in the response.

a|
string
a|
signed_public_key
a|
The SSH public key that results from signing the public key, whether this was user provided or generated by API.
a|
string
|===

== Request example

Requests for this method are similar to the following example:

----
{
    "method": "SignSshKeys",
    "params": {
        "duration": 2,
        "publicKey":<string>
    },
    "id": 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
  "id": null,
  "result": {
    "signedKeys": {
      "keygen_status": <keygen_status>,
      "signed_public_key": <signed_public_key>
    }
  }
}
----

In this example, a public key is signed and returned that is valid for the duration (1-24 hours).

== New since version

12.5
